export const ActionTypes = {
    DEVELOPMENT_NICHES: 'DEVELOPMENT_NICHES',
    DEPARTMENT_NICHES: 'DEPARTMENT_NICHES',
    EMAIL: 'EMAIL',
    PHONE: 'PHONE',
    FIRST_NAME: 'FIRST_NAME',
    LAST_NAME: 'LAST_NAME',
    COMPANY_NAME: 'COMPANY_NAME',
    JOB_TITLE: 'JOB_TITLE',
    IS_MODAL_OPEN: 'IS_MODAL_OPEN',
  };
  